[versions]
freemarker = "2.3.30"
serialization = "1.5.1"
jdk = "17"
kotlin = "2.1.20"
changelog = "2.0.0"
gradleIntelliJPlugin = "2.10.5"
spotless = "6.8.0"
segment = "1.13.2"
junit = "4.13.2"

[libraries]
freemarker = { group = "org.freemarker", name = "freemarker", version.ref = "freemarker" }
serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
segment = { group = "com.segment.analytics.kotlin", name = "core", version.ref = "segment" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
gradleIntelliJPlugin = { id = "org.jetbrains.intellij.platform", version.ref = "gradleIntelliJPlugin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
